set windows-shell := ["pwsh", "-NoLogo", "-NoProfileLoadTime", "-Command"]
test_files := `node -e "console.log(require('glob').globSync('./src/**/*.test.{ts,tsx}').join(' '))"`

build:
  npx rspack --mode production -c ./rspack.config.cjs

dev:
  npx rspack dev --mode production -c ./rspack.config.cjs

test: 
  node --import tsx --import "./src/platform/testing/loader.mjs" --test {{ test_files }}
