set windows-shell := ["pwsh", "-NoLogo", "-NoProfileLoadTime", "-Command"]

build:
  npx rspack --mode production -c ./rspack.config.cjs

dev:
  npx rspack dev --mode production -c ./rspack.config.cjs


test_files := `node -e "console.log(require('glob').globSync('./src/**/*.test.{ts,tsx}').join(' '))"`

test: 
  node --import tsx --test {{ test_files }}
